
services:
  process-video:
    path: process-video

  resources:
    path: resources

  auth:
    path: auth
    params:
      videosS3Name: ${process-video.videosS3Name}
      
  video-ai:
    path: video-ai
    params:
      cognitoUserPoolId: ${auth.cognitoUserPoolId}
      cognitoUserPoolClientId: ${auth.cognitoUserPoolClientId}

  socket:
    path: socket
