
services:
  resources:
    path: resources

  process-video:
    path: process-video
    params:
      rekSNSTopic: ${resources.rekSNSTopic}
      rekRole: ${resources.rekRole}

  process-rek:
    path: process-rek
    params:
      rekSQSQueue: ${resources.rekSQSQueue}

  auth:
    path: auth
    params:
      videosS3Name: ${process-video.videosS3Name}
      
  video-ai:
    path: video-ai
    params:
      cognitoUserPoolId: ${auth.cognitoUserPoolId}
      cognitoUserPoolClientId: ${auth.cognitoUserPoolClientId}

  chat-sessions:
    path: chat-sessions
    params:
      cognitoUserPoolId: ${auth.cognitoUserPoolId}
      cognitoUserPoolClientId: ${auth.cognitoUserPoolClientId}

  # socket:
  #   path: socket
