# TODO some of these names are driving me crazy including the name of the project in general
# at some point should remove all services, refactor names, and redeploy
#   this will break some services using hardcoded names for other services and resources

services:
  resources:
    path: resources

  socket:
    path: socket

  edit-sessions:
    path: edit-sessions

  process-video:
    path: process-video
    params:
      rekSNSTopic: ${resources.rekSNSTopic}
      rekRole: ${resources.rekRole}
      sendMessagesTopicArn: ${socket.sendMessagesTopicArn}

  auth:
    path: auth
    params:
      videosS3Name: ${process-video.videosS3Name}

  process-video-data:
    path: process-video-data
    params:
      rekSQSQueue: ${resources.rekSQSQueue}
      transcriptionSNSArn: ${resources.transcriptionSNSArn}

  process-convert:
    path: process-convert
    params:
      mediaConvertSNSArn: ${resources.mediaConvertSNSArn}

  video-ai:
    path: video-ai
    params:
      agentQueueArn: ${resources.agentQueueArn}

  new-message:
    path: new-message
    params:
      agentQueueArn: ${resources.agentQueueArn}
      agentQueueUrl: ${resources.agentQueueUrl}
