# TODO some of these names are driving me crazy including the name of the project in general
# at some point should remove all services, refactor names, and redeploy
#   this will break some services using hardcoded names for other services and resources

services:
  resources:
    path: resources

  process-video:
    path: process-video
    params:
      rekSNSTopic: ${resources.rekSNSTopic}
      rekRole: ${resources.rekRole}

  process-rek:
    path: process-rek
    params:
      rekSQSQueue: ${resources.rekSQSQueue}

  auth:
    path: auth
    params:
      videosS3Name: ${process-video.videosS3Name}

  video-ai:
    path: video-ai
    params:
      cognitoUserPoolId: ${auth.cognitoUserPoolId}
      cognitoUserPoolClientId: ${auth.cognitoUserPoolClientId}

  chat-sessions:
    path: chat-sessions
    params:
      cognitoUserPoolId: ${auth.cognitoUserPoolId}
      cognitoUserPoolClientId: ${auth.cognitoUserPoolClientId}

  socket:
    path: socket
    params:
      cognitoUserPoolId: ${auth.cognitoUserPoolId}
      statusesTableStreamArn: ${resources.statusesTableStreamArn}

  new-message:
    path: new-message
    params:
      cognitoUserPoolId: ${auth.cognitoUserPoolId}
      cognitoUserPoolClientId: ${auth.cognitoUserPoolClientId}
      videoAIStateMachineArn: ${video-ai.videoAIStateMachineArn}
