org: ipj31
app: video-ai
service: new-message

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    STAGE: ${opt:stage, self:provider.stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - "sqs:SendMessage"
          Resource: ${param:agentQueueArn}

plugins:
  - serverless-offline

functions:
  handle-message:
    name: handle-message-${opt:stage, self:provider.stage}
    handler: handler.handle_message
    environment:
      AGENT_QUEUE_URL: ${param:agentQueueUrl}
    events:
      - httpApi:
          path: /${opt:stage, self:provider.stage}/message
          method: POST
          authorizer:
            type: aws_iam

custom:
  serverless-offline:
    ignoreJWTSignature: true
