org: ipj31
app: video-ai
service: video-ai

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "*"

package: 
  individually: true
  patterns:
    - "!venv/**"

plugins:
  - serverless-offline
  - serverless-python-requirements

functions:
  testing:
    handler: src.handler.testing
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi: 
          path: /testing
          method: POST

custom:
  pythonRequirements:
    layer: true
