org: ipj31
app: video-ai
service: video-ai

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: python3.11
  environment:
    STAGE: ${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "*"

package: 
  individually: true
  patterns:
    - "!venv/**"

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-dotenv-plugin

functions:
  testing:
    handler: src.handler.testing
    events:
      - httpApi: 
          path: /testing
          method: POST

custom:
  pythonRequirements:
    zip: true
    slim: true
    dockerizePip: true
    noDeploy:
      - boto3
      - botocore
