org: ipj31
app: video-ai
service: process-convert
frameworkVersion: "3"
provider:
  name: aws
  region: us-east-1
  runtime: python3.11
  environment:
    STAGE: ${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:*"
            - "sns:*"
          Resource: "*"

functions:
  process:
    name: ${self:service}-${opt:stage, self:provider.stage}-process-convert
    handler: handler.handler
    environment:
      MESSAGES_TOPIC_ARN: ${param:sendMessagesTopicArn}
    events:
      - sns:
          arn: ${param:mediaConvertSNSArn}
