org: ipj31
app: video-ai
service: resources

frameworkVersion: "3"

provider:
  name: aws
  region: us-east-1

# All resources declared here and shared with other services
resources:
  Resources:
    # S3 bucket for videos
    Videos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:app}-${opt:stage, self:provider.stage}-videos
    # Table chat sessions includes mesages and videos in a chat session
    ChatSessions:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:app}-${opt:stage, self:provider.stage}-chat-sessions
        AttributeDefinitions:
          - AttributeName: sessionId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: sessionId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL 
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    Connections:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:app}-${opt:stage, self:provider.stage}-connections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
