org: ipj31
app: video-ai
service: socket

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    STAGE: ${opt:stage, self:provider.stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "*"

package:
  individually: true
  exclude:
    - __pycache__/**
    - authorizer.py
    - notify_user.py
    - handler.py
    - get_temp_password.py

plugins:
  - serverless-offline

functions:
  on-connect-socket:
    name: on-connect-socket-${opt:stage, self:provider.stage}
    handler: handler.on_connect
    package:
      include:
        - handler.py
    events:
      - websocket:
          route: $connect
          authorizer:
            name: socket-authorizer
            identitySource:
              - "route.request.querystring.tempPassword"

  on-disconnect-socket:
    name: on-disconnect-socket-${opt:stage, self:provider.stage}
    handler: handler.on_disconnect
    package:
      include:
        - handler.py
    events:
      - websocket:
          route: $disconnect

  socket-authorizer:
    name: socket-authorizer-${opt:stage, self:provider.stage}
    handler: authorizer.handler
    package:
      include:
        - authorizer.py

  get-temp-password:
    name: get-temp-password-${opt:stage, self:provider.stage}
    handler: get_temp_password.handler
    package:
      include:
        - get_temp_password.py
    events:
      - httpApi:
          path: /${opt:stage, self:provider.stage}/temp-password
          method: GET
          authorizer:
            type: aws_iam

  notify-user:
    name: notify-user-${opt:stage, self:provider.stage}
    handler: notify_user.handler
    package:
      include:
        - notify_user.py
    events:
      - sns: ${self:app}-${opt:stage, self:provider.stage}-send-message
    environment:
      DOMAIN: !Ref WebsocketsApi
      REGION: ${self:provider.region}

resources:
  Outputs:
    sendMessagesTopicArn:
      Value:
        Ref: SNSTopicVideoaidevsendmessage
