org: ipj31
app: video-ai
service: video-ai

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    STAGE: ${opt:stage, self:provider.stage}
  httpApi:
    authorizers:
      cognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${opt:region, self:provider.region}.amazonaws.com/${param:cognitoUserPoolId}
        audience:
          - ${param:cognitoUserPoolClientId}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "mediaconvert:*"
          Resource: "*"

package:
  individually: true
  patterns:
    - "!venv/**"
    - "!**/__pychache__/**"

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-prune-plugin

functions:
  video-ai:
    name: video-ai-${opt:stage, self:provider.stage}
    handler: handler.step_function_testing
    module: src/testing
    environment:
      MEDIA_CONVERT_ROLE_ARN: ${param:mediaConvertRoleArn}

resources:
  Outputs:
    videoAILambdaArn:
      Value:
        Fn::GetAtt:
          - VideoDashaiLambdaFunction
          - Arn

custom:
  pythonRequirements:
    zip: true
    slim: true
    dockerizePip: true
    noDeploy:
      - boto3
      - botocore

  serverless-offline:
    ignoreJWTSignature: true
