org: ipj31
app: video-ai
service: video-ai

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    STAGE: ${opt:stage, self:provider.stage}
  httpApi:
    authorizers:
      cognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${opt:region, self:provider.region}.amazonaws.com/${param:cognitoUserPoolId}
        audience:
          - ${param:cognitoUserPoolClientId}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "*"

package: 
  individually: true
  patterns:
    - "!venv/**"
    - "!**/__pychache__/**"

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-prune-plugin

functions:
  video-ai:
    name: video-ai-${opt:stage, self:provider.stage}
    handler: src.handler.blank_lambda
    events:
      - httpApi: 
          path: /${opt:stage, self:provider.stage}/ai
          method: POST
          authorizer:
            name: cognitoAuthorizer

custom:
  pythonRequirements:
    zip: true
    slim: true
    dockerizePip: true
    noDeploy:
      - boto3
      - botocore
    pipCmdExtraArgs:
      - --platform manylinux2014_x86_64
    
  serverless-offline:
    ignoreJWTSignature: true