org: ipj31
app: video-ai
service: video-ai

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    STAGE: ${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "mediaconvert:*"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "iam:PassRole"
            - "sns:Publish"
          Resource: "*"

package:
  individually: true
  patterns:
    - "!venv/**"
    - "!**/__pychache__/**"
    - "!requirements.txt"

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-dotenv-plugin

functions:
  video-ai:
    name: video-ai-${opt:stage, self:provider.stage}
    handler: src.handler.video_agent
    timeout: 900
    events:
      - sqs:
          arn: ${param:agentQueueArn}
          batchSize: 1
    environment:
      MESSAGES_TOPIC_ARN: ${param:sendMessagesTopicArn}

custom:
  pythonRequirements:
    zip: true
    dockerizePip: true
    noDeploy:
      - boto3
      - botocore
