org: ipj31
app: video-ai
service: edit-sessions

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    STAGE: ${opt:stage, self:provider.stage}
  httpApi:
    authorizers:
      cognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${opt:region, self:provider.region}.amazonaws.com/${param:cognitoUserPoolId}
        audience:
          - ${param:cognitoUserPoolClientId}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "*"

plugins:
  - serverless-offline

package:
  individually: true

# TODO add endpoints to remove videos from a session and delete a session
functions:
  create-chat-session:
    name: create-edit-sessions-${opt:stage, self:provider.stage}
    handler: handle_post.handler
    package:
      include:
        - handle_post.py
    events:
      - httpApi:
          path: /${opt:stage, self:provider.stage}/session
          method: POST
          authorizer:
            name: cognitoAuthorizer

  get-conversation:
    name: get-edit-session-${opt:stage, self:provider.stage}
    handler: handle_get.handler
    package:
      include:
        - handle_get.py
    events:
      - httpApi:
          path: /${opt:stage, self:provider.stage}/session/{sessionId}
          method: GET
          authorizer:
            name: cognitoAuthorizer

  add-video:
    name: add-video-${opt:stage, self:provider.stage}
    handler: handle_add_video.handler
    package:
      include:
        - handle_add_video.py
    events:
      - httpApi:
          path: /${opt:stage, self:provider.stage}/session/{sessionId}/video
          method: POST
          authorizer:
            name: cognitoAuthorizer

custom:
  serverless-offline:
    ignoreJWTSignature: true
