org: ipj31
app: video-ai
service: resources

frameworkVersion: "3"

provider:
  name: aws
  region: us-east-1

# All resources declared here and shared with other services
resources:
  Resources:
    # S3 bucket for videos
    Videos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:app}-${opt:stage, self:provider.stage}-videos
    # Table chat sessions includes mesages and videos in a chat session
    ChatSessions:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:app}-${opt:stage, self:provider.stage}-chat-sessions
        AttributeDefinitions:
          - AttributeName: SessionId
            AttributeType: S
        KeySchema:
          - AttributeName: SessionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1